export const timData = {
  sectors: [
    { runs: 11, highlight: false },
    { runs: 8, highlight: false },
    { runs: 9, highlight: false },
    { runs: 12, highlight: false },
    { runs: 9, highlight: false },
    { runs: 15, highlight: true },
    { runs: 4, highlight: false },
    { runs: 7, highlight: false },
  ],
};

export const bjData = {
  sectors: [
    { runs: 5, highlight: false },
    { runs: 4, highlight: false },
    { runs: 2, highlight: false },
    { runs: 2, highlight: false },
    { runs: 15, highlight: true },
    { runs: 10, highlight: false },
    { runs: 4, highlight: false },
    { runs: 2, highlight: false },
  ],
};

export const mahrajData = {
  sectors: [
    { runs: 0, highlight: false },
    { runs: 0, highlight: false },
    { runs: 0, highlight: false },
    { runs: 0, highlight: false },
    { runs: 0, highlight: false },
    { runs: 2, highlight: true },
    { runs: 0, highlight: false },
    { runs: 0, highlight: false },
  ],
};

export const players = {
  timRobinson: {
    wheelId: ".wagonWheel1",
    legendClass: ".legend1",
    runsLabel: ".player-one .runs-label",
    data: {
      "All Bowlers": {
        ones: [
          15, 45, 75, 90, 105, 120, 135, 165, 180, 195, 210, 225, 240, 270, 300,
          330, 333, 366, 388, 400,
        ],
        twos: [30, 44, 96, 150, 270],
        threes: [121],
        fours: [25, 63, 99, 111, 145, 200],
        fives: [],
        sixes: [12, 85, 250],
        totalRuns: 75,
      },
      "Corbin Bosch": {
        ones: [45, 75, 90, 105, 135],
        twos: [30],
        threes: [],
        fours: [25, 63, 99, 111, 232],
        fives: [],
        sixes: [],
        totalRuns: 27,
      },
      "George Linde": {
        ones: [400],
        twos: [150],
        threes: [],
        fours: [],
        fives: [],
        sixes: [250],
        totalRuns: 9,
      },
      "Gerald Coetzee": {
        ones: [33, 58, 61, 100],
        twos: [],
        threes: [163],
        fours: [138],
        fives: [],
        sixes: [201, 270],
        totalRuns: 23,
      },
      "Kwena Maphaka": {
        ones: [33, 144, 261],
        twos: [],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 3,
      },
      "Lungi Ngidi": {
        ones: [401],
        twos: [323],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 3,
      },
      "Senuran Muthusamy": {
        ones: [110, 123, 180, 204, 280, 300],
        twos: [107, 402],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 10,
      },
    },
  },
  jacob: {
    wheelId: ".wagonWheel",
    legendClass: ".legend2",
    runsLabel: ".player-two .runs-label",
    data: {
      "All Bowlers": {
        ones: [
          1, 3, 3, 31, 39, 40, 119, 135, 149, 168, 296, 300, 301, 310, 349, 171,
        ],
        twos: [80, 81, 190],
        threes: [],
        fours: [245],
        fives: [],
        sixes: [60, 94, 113],
        totalRuns: 44,
      },
      "Corbin Bosch": {
        ones: [90, 105, 135],
        twos: [45],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 5,
      },
      "Gerald Coetzee": {
        ones: [76, 102],
        twos: [],
        threes: [],
        fours: [233],
        fives: [],
        sixes: [301],
        totalRuns: 12,
      },
      "Kwena Maphaka": {
        ones: [77, 98, 164],
        twos: [455],
        threes: [],
        fours: [],
        fives: [],
        sixes: [321],
        totalRuns: 11,
      },
      "Lungi Ngidi": {
        ones: [110, 500],
        twos: [],
        threes: [],
        fours: [],
        fives: [],
        sixes: [343],
        totalRuns: 8,
      },
      "Senuran Muthusamy": {
        ones: [115, 154, 199, 234, 324, 432],
        twos: [10],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 8,
      },
    },
  },
  kashMahraj: {
    wheelId: ".kash-mahraj",
    legendClass: ".legend3",
    runsLabel: ".player-three .runs-label",
    data: {
      "All Bowlers": {
        ones: [101, 150],
        twos: [],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 2,
      },
      "Nathan Ellis": {
        ones: [101, 150],
        twos: [],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 2,
      },
      "Cooper Connolly": {
        ones: [],
        twos: [],
        threes: [],
        fours: [],
        fives: [],
        sixes: [],
        totalRuns: 0,
      },
    },
  },
};

export const widthRanges = {
  ones: { min: 35, max: 55 },
  twos: { min: 45, max: 65 },
  threes: { min: 55, max: 80 },
  fours: { min: 100, max: 105 },
  fives: { min: 70, max: 90 },
  sixes: { min: 105, max: 110 },
};
